from distutils.core import setup

setup(
    name='YATES',
    version='0.1.0',
    author='Mark Wallsgrove, Vladimirs Ambrosovs',
    author_email='mark.wallsgrove@gmail.com',
    packages=[
        'yates',
        'yates.Filters',
        'yates.Discovery',
        'yates.Discovery.STBTester',
        'yates.Discovery.PythonNose',
        'yates.Discovery.PythonNose.DBReader',
        'yates.Discovery.PythonNose.DBReader.Model',
        'yates.Discovery.PythonNose.TestDiscovery',
        'yates.TestEnvironment',
        'yates.TestGather',
        'yates.Test',
        'yates.Network',
        'yates.Utils',
        'yates.Domain',
        'yates.TestDistribution',
        'yates.Results',
        'yates.Results.Model',
        'yates.Results.Loggers'
    ],
    url='http://github.com/smokedice/YATES',
    license='',
    description='Yet Another Test Execution System',
    #long_description=open('README.rst').read(),
    install_requires=[
        "Gnosis==0.1.0",
        "Twisted==12.3.0",
        "argparse==1.2.1",
        "distribute==0.6.24",
        "mechanize==0.2.5",
        "minixsv==0.9.0",
        "peewee==1.0.0",
        "pyasn1==0.1.6",
        "pycrypto==2.6",
        "rsa==3.1.1",
        "wsgiref==0.1.2",
        "zope.interface==4.0.3",
    ],
)
